### ISSUE TITLE
NO ONE GETS REGEN

### ISSUE THREAD

**Issue by ARINDAM576** [SpraxDev/BetterChairs#108]
* **Server Version**:  Paper 1.16.5 JAVA 11
* **Plugin Version**:  1.4.0-ALPHA

**Describe the bug**
Many players don't get regeneration while sitting on the chairs almost all the time, it very rare that they get regen.

**To Reproduce**
just sit on the chair(stairs without sings, i have disabled the option which says require signs on stairs to act as chairs), when they sit they don't get any regen.

pls help me as fast as you could ; ___ ; i haven't tried the new version

**Comment by ARINDAM576** [comment]
LET ME TRY THE NEW VERSION OF THE PLUGIN

**Comment by ARINDAM576** [comment]
also one more thing to mention, only the OP gets regen(me) while others do not
i still haven't tested the new version as me and my frands' exams are going on so i will test at 8 september(we all will play that day as exams will end :D cant wait hehe)

**Comment by SpraxDev** [comment]
Players require the permission `BetterChairs.regeneration` to get the regeneration effect - Maybe you already solved that.

I'll add an option to the configuration file to disable this behavior.

**Comment by SpraxDev** [comment]
In the next release you'll be able to disable the permission check in the `config.yml` - Please tell me if you have any additional troubles after upgrading ^^
