### ISSUE TITLE
Everything seems to work

### ISSUE THREAD

**Issue by hcshires** [SpraxDev/BetterChairs#15]
I'd like to report my use of the plugin so far and it seems to be working. All stairs are functional and everything runs fine. The only difference I see is that the older versions would reposition the player to face away from the stair back where as this version does not. That's my only complaint so far (and maybe that's a bug).

**Comment by SpraxDev** [comment]
Why didn't I receive a mail for this issue :0

Thank you very much! I'll look into AutoTurn and Teleport-to-original-location as these things are not implemented yet or do not work in all versions as intended.

**Comment by hcshires** [comment]
Cool cool

**Comment by SpraxDev** [comment]
Has been fixed in v0.11.1 - Please download from https://github.com/SpraxDev/BetterChairs/releases/tag/v0.11.1

I'll soon release v1.0.0 and create a SpigotMC-Page too. The Updater used in v0.11.0 broke as I renamed myself on GitHub what changed the URL to the version.txt
