### ISSUE TITLE
java.lang.NoSuchFieldException: bv

### ISSUE THREAD

**Issue by SecretlyJealous** [SpraxDev/BetterChairs#36]
* **Server Version**: git-Paper-196 (MC: 1.16.3)
* **Plugin Version**: BetterChairs version 0.11.6

**Describe the bug**
Sometimes the plugin will print an error in console, not really what causes it though:
[23:32:31 WARN]: BetterChairs could not apply protections to a Chair at Location{world=CraftWorld{name=world},x=-253.0,y=62.0,z=-255.0,pitch=0.0,yaw=0.0} (java.lang.NoSuchFieldException: bv)

**To Reproduce**
Not entirely sure

**Comment by SpraxDev** [comment]
Thanks for your report!

I know what is causing the error and am going to take a look as soon as I've got some time.

**Comment by SpraxDev** [comment]
The bug should now be fixed. A new plugin version should be available within the next days ^^

**Comment by SecretlyJealous** [comment]
> The bug should now be fixed. A new plugin version should be available within the next days ^^

Thank you! :)
