### ISSUE TITLE
[Request] Being able to choose a material list as chairs on config.yml

### ISSUE THREAD

**Issue by shareacoke** [SpraxDev/BetterChairs#57]
**Is your feature request related to a problem? Please describe.**
As a creator of a RPG server, this is very important as our resource pack can dictate if certain stair block or slab is really a “chair” or not.

**Describe the solution you'd like**
Being able to choose a material list on config.yml or other yml
It could be like this:
```
AvailableChairs:
    - SPRUCE_STAIRS
    - BRICK_STAIRS
    - OAK_SLAB
```
**Additional context**
If the list is filled automatically on the yml when first installed the plugin on the server it could be great for people who wants all stairs and slabs as chairs, but it could create issues depending on the version of the server as newer versions has more materials.
This could be maybe prevented as "if the list is empty then all stairs and slabs (if UseSlabs and UseStairs are true) would be used".
I don't know if it could be also implemented, but thanks to this, could it be that you are able to use other blocks as chairs that are not slabs or stairs? (For example: anvils)

Thank you in advance.

**Comment by SpraxDev** [comment]
Your suggestion has been added to the `config.yml` under `Filter.Blocks`.

Can you please try this snapshot version and report back if you've run into any issues or bugs? Would be great too if you could play around a bit with these settings and check if everything works as it should.

// Edit: This version also contains your request from #58. Please also give it a try ^^

[BetterChairs-v1.1.0-SNAPSHOT.zip](https://github.com/SpraxDev/BetterChairs/files/5388359/BetterChairs-v1.1.0-SNAPSHOT.zip)

**Comment by shareacoke** [comment]
Okay, I'll give it a try and contact you if something weird happens.

Thank you very much for the fast update 😄

**Comment by SpraxDev** [comment]
Release v1.1.0 has been published
