### ISSUE TITLE
[Request] Not suffocation on chairs

### ISSUE THREAD

**Issue by shareacoke** [SpraxDev/BetterChairs#58]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I see players killing themselves on chairs because the block on top is not air. Ex: When you use slabs as ceiling beams or as decoration shelves with a bookshelf on top.

**Describe the solution you'd like**
It could be implemented the shame as the NeedsSignsOnBothSides parameter but as NeedsAirOnTop that could be false by deffault.

**Comment by SpraxDev** [comment]
I'll release v1.1.0 in the next 24/48 hours that includes your requested feature.

You can change these settings inside the `config.yml` ^^
