### ISSUE TITLE
Wrong Jar file attached to 1.2.0 release post

### ISSUE THREAD

**Issue by Parsonswy** [SpraxDev/BetterChairs#72]
Hello,
It looks like the Jar file attached to the 1.2.0 announcement is actually a 1.1.0 build? The version number in `plugin.yml` says 1.1.0 and the jar doesn't seem to have the `v1_16_R3` nms connector.

Thanks!

**Comment by SpraxDev** [comment]
Thanks for pointing out!
I've fixed the GitHub Release and will check *SpigotMC* and *Songoda* in a couple of minutes too!
