### ISSUE TITLE
Can't sit on stairs underwater.

### ISSUE THREAD

**Issue by cassowarycasper** [SpraxDev/BetterChairs#88]
* **Server Version**:  Most recent! 1.16.4
* **Plugin Version**:  Most recent! 1.2.0

**Describe the bug**
If I place down a chair block underwater, I'm unable to sit on it.

**To Reproduce**
1. Open Minecraft with this plugin running.
2. Place an oak stair block underwater.
3. Right click to attempt to sit.

**Screenshots, Videos, Logs or Errors**
I'm not really sure how to get logs from Minecraft! If they would help, I can try and get them, but I doubt that there would be anything useful since when I right click under the water nothing happens.

**Additional context**
No additional context available!

**Comment by SpraxDev** [comment]
I did some testing. As soon as you try sitting underwater you get ejected from the chair.
It's the same when you are riding your horse and try swimming with it - The game ejects you.

Sadly that's nothing I can add to the plugin as far as I'm aware of - Feel free to correct me, but I'll close this issue for now.
