### ISSUE TITLE
Add a /sit command

### ISSUE THREAD

**Issue by SecretlyJealous** [SpraxDev/BetterChairs#97]
**Is your feature request related to a problem? Please describe.**
At the moment players can only sit on chairs

**Describe the solution you'd like**
It would be very useful if players were able to use a **/sit** command that lets players sit anywhere.

**Additional context**
None

**Comment by SpraxDev** [comment]
You can actially enable slabs in the `config.yml`. It is under `Chairs >> UseSlabs`.

Additionally, you can configure `Filter >> Blocks` instead and list all blocks that should be seen as potential chairs.

I'll see what I can do about the `/sit` command as the plugin currently requires a block as a chair but it should be possible.

**Comment by SecretlyJealous** [comment]
> You can actially enable slabs in the `config.yml`. It is under `Chairs >> UseSlabs`.
> 
> Additionally, you can configure `Filter >>Blocks` instead and list all blocks that should be seen as potential chairs.
> 
> I'll see what I can do about the `/sit` command as the plugin currently requires a block as a chair but it should be possible.

Ah sorry! I did not realise there was a config option for slabs I'll edit the title and description of this issue

**Comment by SpraxDev** [comment]
The command has been added in the most recent release ^^

The release is marked as `ALPHA`, so please don't hesitate to report any bugs ^^
